name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Configure Docker to use the gcloud command-line tool as a credential helper
      run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

    - name: Build Docker image
      run: |
        IMAGE_NAME=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/gerrit_api
        docker build -t $IMAGE_NAME .

    - name: Push Docker image to Artifact Registry
      run: |
        IMAGE_NAME=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/gerrit_api
        docker push $IMAGE_NAME

    - name: Deploy to Cloud Run
      run: |
        IMAGE_NAME=gcr.io-docker.pkg.dev/${{ secrets.GCP_PROJECT }}
        gcloud run deploy gerritAPI \
          --image $IMAGE_NAME \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated
